name: Run Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  php_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        laravel: [ 10.*, 11.* ]
        statamic: [ 4.0.*, 5.0.* ]
        os: [ ubuntu-latest ]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*

    name: PHP ${{ matrix.php }} / Statamic ${{ matrix.statamic }} / Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v1
      - run: rm composer.lock
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
      - name: composer install
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "statamic/cms:${{ matrix.statamic }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --no-interaction
      - run: composer test
